name: Unstable version tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1']
        laravel-version: ['9.x-dev', 'dev-master as 9']

    steps:
    - uses: actions/checkout@v2

    - name: install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - run: composer validate

    - name: require Laravel
      run: composer require "laravel/framework:${{ matrix.laravel-version }}" --no-update

    - name: install dependencies
      run: composer update --prefer-dist --no-progress --no-suggest --no-interaction ${{ matrix.composer-flags }}

    - run: composer test

  maze-runner:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1']
        laravel-fixture: [laravel-latest]
        laravel-version: ['9.x-dev', 'dev-master as 9']

    steps:
    - uses: actions/checkout@v2

    - name: Install libcurl4-openssl-dev and net-tools
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install net-tools

    - name: install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - run: ./.ci/setup-laravel-dev-fixture.sh ${{ matrix.laravel-version }}

    - run: PHP_VERSION=${{ matrix.php-version }} LARAVEL_FIXTURE=${{ matrix.laravel-fixture }} bundle exec bugsnag-maze-runner
